# Site settings
title: Utveckling av molnbaserade applikationer
subtitle: PGBSNH20
description: |
    Kursen syftar till att den studerande utvecklar kunskap 
    om och förståelse för hur man utvecklare och driver 
    applikationer som kör i molnet, samt hur man som utvecklare 
    jobbar i området emellan utveckling och drift 
    (populärt kallat DevOps).
baseurl: "/PGBSNH20-molnapplikationer/" # the subpath of your site, e.g. /blog/
url: "https://pgbsnh20.github.io/PGBSNH20-molnapplikationer" # the base hostname & protocol for your site
githubdir: PGBSNH20/PGBSNH20-molnapplikationer"
lms-name: Ping Ping
lms-url: https://yh.pingpong.se/courseId/12109/content.do?id=4887498
course-start: 2021-09-06
course-end: 2021-10-15
timezone: Europe/Stockholm


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
